export const APIHHRM = "http://localhost:3000";
export const apiPaths = {
  ACCOUNTS: "/accounts",
  USERS: "/users",
  ROLES: "/roles",
  POSITIONS: "/positions",
  POSITION_ALLOWANCE: "/position_allowance",
  LEAVE_HISTORIES: "/leave-histories",
  LEAVES: "/leaves",
  INSURANCES: "/insurances",
  USER_INSURANCE: "/user_insurance",
  EVALUATES: "/evaluates",
  DEPARTMENTS: "/departments",
  ALLOWANCES: "/allowances",
  OVERTIMES: "/overtimes",
  OVERTIME_HISTORIES: "/overtime-histories",
  CONTRACTS: "/contracts",
  CONTRACT_HISTORIES: "/contract-histories",
  MEDICAL_TRAINING_RESULTS: "/medical-training-results",
  NURSING_TRAINING_RESULTS: "/nursing-training-results",
  SALARY_HISTORY: "/salary-histories",
  RECRUITMENT_POSTS: "/recruitment-posts",
  ANNOUNCEMENT_POSTS: "/announcement-posts",
};
